trigger:
  - main

pool:
  name: 'Default'  # Fixed pool syntax

variables:
  NODE_VERSION: '18.x'

steps:
  # Verify Node.js is available
  - script: |
      echo "Checking Node.js..."
      node --version
      npm --version
      echo "Current directory: %CD%"
      dir
    displayName: "Check Node.js and Environment"

  # Build Server (Backend) with better error handling
  - script: |
      echo "Starting server build..."
      if exist server (
        echo "Server directory found, entering..."
        pushd server
        echo "Current directory: %CD%"
        dir
        if exist package.json (
          echo "Installing server dependencies..."
          npm install
          echo "Running server build..."
          npm run build 2>nul || echo "No build script found - that's okay"
        ) else (
          echo "No package.json found in server directory"
        )
        popd
      ) else (
        echo "Server directory not found in: %CD%"
        echo "Available directories:"
        dir /b
        exit /b 1
      )
    displayName: 'Build Server (Backend)'

  # Build Client (Frontend) with better error handling
  - script: |
      echo "Starting client build..."
      if exist client (
        echo "Client directory found, entering..."
        pushd client
        echo "Current directory: %CD%"
        dir
        if exist package.json (
          echo "Installing client dependencies..."
          npm install
          echo "Running client build..."
          npm run build
        ) else (
          echo "No package.json found in client directory"
          exit /b 1
        )
        popd
      ) else (
        echo "Client directory not found in: %CD%"
        echo "Available directories:"
        dir /b
        exit /b 1
      )
    displayName: 'Build Client (Frontend)'

  # Deploy Server (Backend)
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-backend'
      package: '$(System.DefaultWorkingDirectory)/server'
    displayName: 'Deploy Server (Backend)'

  # Deploy Client (Frontend)
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-frontend'
      package: '$(System.DefaultWorkingDirectory)/client/build'
    displayName: 'Deploy Client (Frontend)'