trigger:
  - main

pool:
  default
variables:
  NODE_VERSION: '18.x'

steps:
  - script: node --version
    displayName: "Check local Node.js version"

  # Build Backend
  - script: |
      cd backend
      npm install
      npm run build || echo "No build step for backend"
    displayName: 'Build Backend'

  # Build Frontend
  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Build Frontend'

  # Deploy Backend
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-backend'
      package: '$(System.DefaultWorkingDirectory)/backend'

  # Deploy Frontend
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-frontend'
      package: '$(System.DefaultWorkingDirectory)/frontend/build'