trigger:
  - main

pool:
  name: 'Default'

variables:
  NODE_VERSION: '18.x'

steps:
  - script: node --version
    displayName: "Check local Node.js version"

  # Build Server (Backend) - Smart build detection
  - script: |
      cd server
      npm install
      
      REM Check if build script exists in package.json
      findstr /C:"\"build\"" package.json >nul 2>&1
      if errorlevel 1 (
        echo "No build script found in package.json - skipping build step"
      ) else (
        echo "Build script found - running npm run build"
        npm run build
      )
    displayName: 'Build Server (Backend)'

  # Build Client (Frontend)
  - script: |
      cd client
      npm install
      npm run build
    displayName: 'Build Client (Frontend)'

  # Deploy Server
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-backend'
      package: '$(System.DefaultWorkingDirectory)/server'

  # Deploy Client
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-frontend'
      package: '$(System.DefaultWorkingDirectory)/client/build'