trigger:
  - main

pool:
  name: 'Default'

steps:
  - script: node --version
    displayName: "Check Node.js version"

  # Server build (keep this the same since it's working)
  - script: |
      cd server
      npm install
      npm run build || echo "No build step for server"
    displayName: 'Build Server'
    continueOnError: true

  # Focus on client build with maximum debugging
  - script: |
      echo "====== CLIENT BUILD DIAGNOSIS ======"
      cd client
      
      echo "Step 1: Check what's in client directory"
      dir
      
      echo "Step 2: Check package.json"
      if exist package.json (
        type package.json
      ) else (
        echo "ERROR: No package.json found!"
        exit /b 1
      )
      
      echo "Step 3: Install dependencies"
      npm install
      
      echo "Step 4: Show available scripts"
      npm run
      
      echo "Step 5: Try to build (showing all output)"
      npm run build 2>&1 && (
        echo "BUILD SUCCESS!"
        echo "Checking what was created:"
        dir
      ) || (
        echo "BUILD FAILED - that's why no build directory exists"
        echo "Current directory after failed build:"
        dir
      )
      
    displayName: 'Client Build Diagnosis'

  # Deploy server (this worked before)
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-backend'
      package: '$(System.DefaultWorkingDirectory)/server'
    displayName: 'Deploy Server'
    continueOnError: true

  # Try to deploy client - check multiple possible locations
  - script: |
      cd client
      echo "Looking for build output..."
      if exist build (
        echo "Found build directory - using that"
        echo ##vso[task.setvariable variable=CLIENT_PATH]$(System.DefaultWorkingDirectory)/client/build
        echo ##vso[task.setvariable variable=DEPLOY_CLIENT]true
      ) else if exist dist (
        echo "Found dist directory - using that (Vite build)"
        echo ##vso[task.setvariable variable=CLIENT_PATH]$(System.DefaultWorkingDirectory)/client/dist
        echo ##vso[task.setvariable variable=DEPLOY_CLIENT]true
      ) else (
        echo "No build directory found - will deploy source code"
        echo ##vso[task.setvariable variable=CLIENT_PATH]$(System.DefaultWorkingDirectory)/client
        echo ##vso[task.setvariable variable=DEPLOY_CLIENT]true
      )
    displayName: 'Determine Client Deploy Path'

  # Deploy client
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'mern-ecommerce application'
      appName: 'mern-ecommerce-frontend'
      package: '$(CLIENT_PATH)'
    displayName: 'Deploy Client'
    condition: eq(variables['DEPLOY_CLIENT'], 'true')